### PR TITLE
Fixed some of the French translations

### PR DESCRIPTION
**Pull request by Tititesouris**
I fixed some French translations. There is still work to do, including in the files I changed, but for that the original English should be fixed first, as it also contains many mistakes which cannot be corrected from context.

### CODE REVIEW

**Comment by jlooper** [comment]
Hi, thank you, which English strings were incorrect? I can take a look

**Comment by Tititesouris** [comment]
For instance en-gallery.json, the strings yearNotSelected and notResultsByYear don't make grammatical sense, and notEvents is just kind of nonsensical.

**Comment by jlooper** [comment]
hi, I fixed up the gallery English and edited their usage. The most important translations we have, though, are the home page and About page, so I will wait on merging this PR until those are added, thank you!

**Comment by Tititesouris** [comment]
about page:
"With chapters worldwide, you can probably find a group near you!" -> What are chapters?
"women developers, and those who identify as such" -> This is kind of saying that those who identify as women are not women, which I don't believe you would agree with.

Please keep in mind that I would like this PR to count towards Hacktoberfest ;)
If you can answer those 2 questions then I can push the final translations.

**Comment by jlooper** [comment]
Chapters are the folks on our Teams page. They organize local events.

**Comment by jlooper** [comment]
These older strings might help https://github.com/FrontEndFoxes/website/blob/main/assets/translations/about.js

**Comment by Tititesouris** [comment]
Thanks for the quick response!
Here are my latest changes :)

**Review by jlooper — COMMENTED** [review]
let's keep the word 'apprendre' as we are mostly folks who learn together
also, the change to the content string with the extra space isn't necessary, thanks
also, Évènements is misspelled, the accents were correct originally as per collins dictionary

**Review by jlooper — CHANGES_REQUESTED** [review]
in the about translation, I think we need to watch for feminine vs. masculine nouns. We are women teaching women so we should actually use 'organisatrice' and 'participantes' 

All the spaces before punctuation should be removed, thanks

**Comment by Tititesouris** [comment]
Apprendre -> fixing it
content string extra space -> Not sure what you are referencing?
Événement -> Since 1990 it can be spelled both ways, Évènement being the reformed version which matches the pronunciation. Up to you which version you pick

**Review by jlooper — CHANGES_REQUESTED** [review]
communautée is misspelled

**Comment by Tititesouris** [comment]
Spaces before punctuation is how it is spelled in French, removing it makes it grammatically incorrect.
I will update nouns to be feminine :) They were male/default before so I figured I would leave them that way

**Comment by Tititesouris** [comment]
For mentors, which as far as I understand do not have to identify as women, would you rather I use the parenthesis inclusive writing, the dash-point inclusive writing, or default to male?
Examples:
Votre travail consiste à être présent(e)
Votre travail consiste à être présent·e
Votre travail consiste à être présent

**Comment by jlooper** [comment]
wow, the punctuation rules sent me down a rabbit hole, it's complicated! https://www.iwillteachyoualanguage.com/learn/french/french-tips/french-punctuation - and it looks like it _depends_ on the punctuation, that's totally wild. Let's at least not add spaces before and after periods. 

For mentors, let's use this; `Votre travail consiste à être présent(e)`

I guess if we are using inclusive nouns let's go for the 'reformed' spelling of events. TIL!

Thanks,
Jen

**Comment by Tititesouris** [comment]
Correct, apart from the full stop and the comma, every other punctuation has a space before it. Technically it's not exactly a space character, but I would not recommend using a non-ascii space character, especially because everyone on the French internet uses just the normal space character.
I found a few more typos and spelling errors which I fixed.
Let me know if there's anything else you need changed. If not I'll have a quick final read-through to make sure it reads well.

**Comment by jlooper** [comment]
Is there a good way to say this: '501(c)(3) Public Charity' - we an also say nonprofit. Let's make sure we keep those parentheses as is. 
`Sponsoring Front-End Foxes` - any better way to say this?
Not loving 'animatrices' - sounds like cocktail waitresses :D - how about 'Leaders régionaux'

I think this is looking nice, thanks. Do you want to connect it to the dropdown in the nav? There is a document on how to complete a new language implementation

**Comment by Tititesouris** [comment]
501 -> I was basing myself on the French wiki page for this https://fr.wikipedia.org/wiki/501c which spells it without sprentheses. I don't know legally what that means though. I would say what it is in French followed by the whole "501(c)(3) Public Charity"

Animatrices -> This is a very common French word, including in the female version. It means someone who entertains and guides a group of apprentices. The problem with leaders régionaux/locaux is that is it default masculine, and there is no pretty way to make it inclusive.

Unfortunately I can't really spend more time to connect it to the dropdown, I just wanted to make sure the translation was up to a good state because this project sounds interesting :)

**Comment by jlooper** [comment]
ok, it sounds good! thank you, I will test locally and then merge!

**Comment by jlooper** [comment]
Merci bien!!

**Comment by Tititesouris** [comment]
Thank you and "Bon courage !" with the project! :)

**Comment by jlooper** [comment]
it's live :) if you send me an email at jen @ frontendfoxes.org I'll send you a little care package :) - tell me your tshirt size

**Pull request merged**
