### PR TITLE
Homepage: Events

### PR DESCRIPTION
**Pull request by rsales**
## Types of changes
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Hi @jlooper, I'm opening the PR for the following feature implemented in the project requested in the issue [Homepage: Events](https://github.com/FrontEndFoxes/ff-web/issues/8) 🙂

#### I made the following changes:
* Generated standard colors within `tailwind.config`;
* Organized some `folder` structures;
* Organized `folders` for component groups;
* Create the `CardEvent.vue` component to be reusable;
* Separated the sections of the homepage into three components;
* Include lib [dayjs](dayjs) in the project;
* Include first `mixin`in project `truncate.js`;
* Setting `max-height` and `min-height` for cards events

## Image Feature

Screen Shot 2020-10-08 at 00 19 03

### CODE REVIEW

**Comment by jlooper** [comment]
wow! amazing work, I love it!

I just have one comment...could we get the cards forced to be the same height, regardless of the content? otherwise, spectacular enhancement!

**Comment by rsales** [comment]
> wow! amazing work, I love it!
> 
> I just have one comment...could we get the cards forced to be the same height, regardless of the content? otherwise, spectacular enhancement!

Thanks @jlooper, yes I can define cards with fixed heights and i will also take the opportunity to add a `truncate` in the event description. 🙂

**Comment by rsales** [comment]
Hi @jlooper, I just made the requested changes define a `max-height` for the **card** and also created a **mixin** `truncate.js` to be able to reuse the `truncate function` in the texts.

**Comment by jlooper** [comment]
Spectacular. Thank you!!!

**Pull request merged**
