### PR TITLE
Issue 38/about us

### PR DESCRIPTION
**Pull request by mariajcb**
### Problem
About us page could use some sprucing up!

### Solution
BraydenTW created a design here: https://github.com/FrontEndFoxes/ff-web/issues/38.
I adjusted the design to use FF colors (blue and orange), added some copy, and rejiggered it for mobile. I also kept font variation to a minimum.

### Notes
-All the translations have trickled down, except two places: "Who We Are"  heading and "our preferred donation option" for github.
-is there a link to give us a software sponsorship? I gave it the link animation, but I don't actually know if it's supposed to lead somewhere.

### Screenshots
![Screenshot_2020-12-07 About Front-End Foxes](https://user-images.githubusercontent.com/19481583/101409568-4e51c480-389b-11eb-80d1-5b26f35a48bf.png

### CODE REVIEW

**Comment by jlooper** [comment]
hi, this is looking very nice! Two things:

- can we bump up the font in the two 'notes' areas, as it's a bit hard to read
- can we choose two images from the gallery (any year) instead of the stock photos?

thanks!!

**Comment by mariajcb** [comment]
- I agree, I'll bump it up
- I'll choose a couple

**Comment by mariajcb** [comment]
@jlooper I was trying to get some action shots of people coding, but most of them are dark, blurry, or unflattering to the participants. Do you have any favorites from the gallery?

**Comment by jlooper** [comment]
How about we ask the community?

**Comment by mariajcb** [comment]
Didn't get much traction with the community! Michele sent in a photo; the other one is just from the gallery.

Screen Shot 2020-12-18 at 4 22 04 PM

**Pull request closed without merging**
