### PR TITLE
Events Gallery (issue #5)

### PR DESCRIPTION
**Pull request by alxmcr**
1. Created a new file:
2. Created new Vue components: 
- EventCard
- EventsGroup
- YearsGroup
3. Updated Gallery.vue

### CODE REVIEW

**Review by jlooper — COMMENTED** [review]
quick question, is it necessary to duplicate? and let's check on these lifecycle hooks in Vue 3

otherwise thank you!!

created() {
		this.initialize();
	},
	mounted() {
		this.initialize();
	},

**Comment by alxmcr** [comment]
> quick question, is it necessary to duplicate? and let's check on these lifecycle hooks in Vue 3
> 
> otherwise thank you!!
> 
> created() {
> this.initialize();
> },
> mounted() {
> this.initialize();
> },

Oops so sorry! It's only necessary "mounted()" method. I feel bad and ashamed :( . I should have removed initialize() method. I'm sorry! If you want I can remove this.

**Comment by jlooper** [comment]
no worries! I'll merge and do the edit. Thank you again!!

**Comment by alxmcr** [comment]
> no worries! I'll merge and do the edit. Thank you again!!

Oh! You're so kind. I really appreciate it... I'm so sorry for my mistakes :( ... Thank you so much 😊!

**Pull request merged**
