### PR TITLE
Team page - issue #6: Populate the team members

### PR DESCRIPTION
**Pull request by alxmcr**
Updated descriptions, websites, Twitter's accounts, and completed the names for team members.

### CODE REVIEW

**Comment by jlooper** [comment]
Wow! This is great! We do need to add all our leads from frontendfoxes.org teams page but I'm accepting this PR!

**Comment by alxmcr** [comment]
I'm so sorry @jlopper 😢 , I've added all leaders now on **[this website](https://frontendfoxes-review.netlify.app)** where you could see the result (I won't make another pull request because I'm participating in **Hacktoberfest**. **It's not correct** that I have two pull requests for the same issue.).

Could you please review the result? 🙏  if you have any time. I'll appreciate it 🙂. Well, I don't know, **is it the correct solution?** I'm sorry again 😢

I will pay attention to your comments. Thanks!

**Comment by alxmcr** [comment]
> Wow! This is great! We do need to add all our leads from frontendfoxes.org teams page but I'm accepting this PR!

I'm so sorry @jlopper 😢 , I've added all leaders now on this website where you could see the result (I won't make another pull request because I'm participating in Hacktoberfest. It's not correct that I have two pull requests for the same issue.).

Could you please review the result? 🙏 if you have any time. I'll appreciate it 🙂. Well, I don't know, is it the correct solution? I'm sorry again 😢

I will pay attention to your comments. Thanks!

**Comment by jlooper** [comment]
Hi! Thank you so much for this work!! I can create a new issue for you to complete what you started, what do you think?

**Comment by alxmcr** [comment]
> Hi! Thank you so much for this work!! I can create a new issue for you to complete what you started, what do you think?

Of course! I would like to do it 🙂👍  Thank you so much! I really appreciate it 🙏. 

I'm sorry, please about images 🙏, I wrote this [comment](https://github.com/FrontEndFoxes/ff-web/issues/6#issuecomment-702519695), could you please give me more information about hosting images in Cloudinary?

Thanks!

**Pull request merged**
